name: Auto PR Comment

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add automated comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@claude Please analyze this pull request with a focus on detecting any new features added to praisonaiagents. Your tasks: 1) Review the PR changes and identify any new features, classes, methods, or functionalities added to praisonaiagents 2) Create comprehensive documentation for each new feature discovered 3) Ensure backward compatibility and that no existing features are removed 4) If fixes are needed, implement minimal code changes 5) Use @web to search for latest documentation or version information if needed 6) Remove any tested code as only documentation is required 7) After making changes, review them again for quality assurance. Priority: Focus on cataloging new features so we can maintain up-to-date documentation based on the number of features being added to the project. Do not include test code in the final output.'
            })
